import type { BaseIdea } from './ideaTypes.js';

/**
 * The generator's corpus. Every idea carries a `why` — the emotional reason
 * it might land — because that is what turns a list into a suggestion.
 *
 * Pure data, deliberately. It is imported both by the browser and by
 * `api/recommend-ideas.ts`, which is what lets the server decide for itself
 * what may be recommended instead of trusting a list the browser sent it. So
 * nothing here imports the `@/` alias, React, or the photo helper: the image
 * is a seed, and the URL is built on the phone.
 */
export const DATE_IDEAS: BaseIdea[] = [
  {
    id: 'i-pasta',
    title: 'Cook one dish from scratch',
    emoji: '🍝',
    description:
      'Pick something neither of you has made before. One recipe, one bottle of wine, no phones on the counter.',
    duration: 120,
    cost: 25,
    prep: 'Groceries on the way home',
    why: 'Cooking together gives you something to do with your hands while you talk — the conversation goes further than it does across a restaurant table.',
    vibes: ['romantic', 'creative', 'relaxing'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening'],
    category: 'food',
    mode: 'in_person',
    familyId: 'cook',
    imageSeed: 'pasta',
  },
  {
    id: 'i-listening',
    title: 'The listening hour',
    emoji: '🎧',
    description:
      'Each of you queues three songs that meant something this year. Play them, and say why after each one.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'You learn more about someone from the songs they chose than from asking how their week was.',
    vibes: ['romantic', 'relaxing', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'conversation',
    mode: 'either',
    imageSeed: 'records',
  },
  {
    id: 'i-nightwalk',
    title: 'Walk somewhere with no destination',
    emoji: '🌙',
    description:
      'Leave the house after dinner and turn whichever way looks more interesting. Come back when you feel like it.',
    duration: 60,
    cost: 0,
    prep: 'Coats',
    why: 'Walking side by side is easier than sitting face to face. Harder things get said on a walk.',
    vibes: ['romantic', 'relaxing'],
    setting: 'out',
    energy: 'low',
    weather: ['any', 'cold', 'warm'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'nightwalk',
  },
  {
    id: 'i-market',
    title: 'Breakfast at the market',
    emoji: '🥐',
    description:
      'Go early, buy whatever looks best, eat some of it standing up, take the rest home for lunch.',
    duration: 120,
    cost: 30,
    prep: 'Set an alarm',
    why: 'Mornings together are rarer than evenings, and they feel like a small act of rebellion against the week.',
    vibes: ['relaxing', 'fun'],
    setting: 'out',
    energy: 'medium',
    weather: ['sun', 'warm', 'any'],
    spontaneity: 'planned',
    dayparts: ['morning', 'brunch'],
    category: 'food',
    mode: 'in_person',
    imageSeed: 'market',
  },
  {
    id: 'i-gallery',
    title: 'One room of a museum',
    emoji: '🖼️',
    description:
      'Not the whole thing. Pick a single room and stay in it. Choose a piece each and tell the other why.',
    duration: 90,
    cost: 24,
    prep: 'Check closing time',
    why: 'A shared reference point you will both come back to later — "the one with the blue horse".',
    vibes: ['creative', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['rain', 'cold', 'any'],
    spontaneity: 'planned',
    dayparts: ['afternoon'],
    category: 'culture',
    mode: 'in_person',
    imageSeed: 'gallery',
  },
  {
    id: 'i-bath',
    title: 'Slow evening in',
    emoji: '🕯️',
    description: 'Candles, hot water, a playlist, and an agreement that neither of you checks a screen.',
    duration: 90,
    cost: 10,
    prep: 'Clean the bathroom, honestly',
    why: 'Physical closeness without the pressure of it going anywhere in particular.',
    vibes: ['romantic', 'relaxing'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'candles',
  },
  {
    id: 'i-bookshop',
    title: 'Buy each other a book',
    emoji: '📚',
    description:
      'Twenty minutes, separate aisles, one book each under €15. Write something on the first page before you hand it over.',
    duration: 75,
    cost: 30,
    prep: 'None',
    why: 'Choosing a book for someone is a small argument that you know them.',
    vibes: ['creative', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['rain', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon'],
    category: 'culture',
    mode: 'in_person',
    imageSeed: 'bookshop',
  },
  {
    id: 'i-sunrise',
    title: 'Get up for the sunrise',
    emoji: '🌅',
    description: 'Somewhere with a view. Bring coffee in a thermos and a blanket. Go back to bed after.',
    duration: 120,
    cost: 5,
    prep: 'Find the spot the night before',
    why: 'Effort is the point. You will remember the getting up more than the sky.',
    vibes: ['romantic', 'adventurous'],
    setting: 'out',
    energy: 'medium',
    weather: ['sun', 'cold', 'warm'],
    spontaneity: 'planned',
    dayparts: ['morning'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'sunrise',
  },
  {
    id: 'i-oldphotos',
    title: 'Go through the old photos',
    emoji: '📷',
    description:
      'Scroll back to the first year. Pick five you had both forgotten and say what you remember about that day.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'Remembering together is one of the few things that reliably makes couples feel closer.',
    vibes: ['romantic', 'relaxing'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'conversation',
    mode: 'either',
    imageSeed: 'oldphotos',
  },
  {
    id: 'i-newbar',
    title: 'The bar you always walk past',
    emoji: '🍸',
    description: 'One drink each, at the place you have said "we should try that" about for a year.',
    duration: 90,
    cost: 35,
    prep: 'None',
    why: 'Small unfamiliar rooms make you talk to each other differently.',
    vibes: ['fun', 'romantic'],
    setting: 'out',
    energy: 'medium',
    weather: ['any', 'rain', 'cold', 'warm'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'food',
    mode: 'in_person',
    imageSeed: 'bar',
  },
  {
    id: 'i-cinemahome',
    title: 'Home cinema, properly',
    emoji: '🎬',
    description:
      'Not background TV. Lights off, phones in another room, something one of you loves and the other has never seen.',
    duration: 150,
    cost: 12,
    prep: 'Snacks',
    why: 'Showing someone the film you grew up with is a way of showing them where you came from.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['rain', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'culture',
    mode: 'either',
    familyId: 'film',
    imageSeed: 'cinema',
  },
  {
    id: 'i-pottery',
    title: 'Be beginners at something',
    emoji: '🏺',
    description: 'A single class — pottery, dancing, printmaking. Whatever has an open evening slot.',
    duration: 150,
    cost: 60,
    prep: 'Book a few days ahead',
    why: 'Being bad at something in front of each other is disarming in a way that going for dinner is not.',
    vibes: ['creative', 'fun'],
    setting: 'out',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'in_person',
    imageSeed: 'pottery',
  },
  {
    id: 'i-picnic',
    title: 'Dinner outside',
    emoji: '🧺',
    description: 'Whatever is in the fridge, taken to a park bench or a rooftop. It counts.',
    duration: 90,
    cost: 15,
    prep: 'A blanket',
    why: 'Same food, different room, entirely different evening.',
    vibes: ['relaxing', 'romantic', 'fun'],
    setting: 'out',
    energy: 'low',
    weather: ['sun', 'warm'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'food',
    mode: 'in_person',
    imageSeed: 'picnic',
  },
  {
    id: 'i-questions',
    title: 'Twenty questions you have never asked',
    emoji: '💬',
    description:
      'Take turns. No question about logistics, work, or family admin allowed. Keep going until one of you is surprised.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'Long-term couples stop asking questions. Most of the answers have quietly changed.',
    vibes: ['romantic', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'conversation',
    mode: 'either',
    imageSeed: 'questions',
  },
  {
    id: 'i-swim',
    title: 'Cold water, then something warm',
    emoji: '🌊',
    description: 'A lake, the sea, or the pool down the road. Follow it immediately with soup or a sauna.',
    duration: 180,
    cost: 20,
    prep: 'Towels',
    why: 'Doing something slightly uncomfortable together builds a specific kind of closeness.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'warm', 'cold'],
    spontaneity: 'planned',
    dayparts: ['morning', 'afternoon'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'coldswim',
  },
  {
    id: 'i-bike',
    title: 'Ride out to lunch',
    emoji: '🚲',
    description: 'Pick somewhere 45 minutes away by bike. Eat, ride back the long way.',
    duration: 240,
    cost: 40,
    prep: 'Check the tyres',
    why: 'A whole afternoon, no scheduling, and you arrive hungry enough to enjoy anything.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'warm'],
    spontaneity: 'planned',
    dayparts: ['brunch', 'afternoon', 'wholeday'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'bikeride',
  },
  {
    id: 'i-letters',
    title: 'Write each other a letter',
    emoji: '✉️',
    description:
      'Twenty minutes, on paper, in different rooms. Swap, read in silence, then say one thing about what you read.',
    duration: 45,
    cost: 0,
    prep: 'Paper and two pens',
    why: 'On paper you say the things that dissolve when you try to say them out loud.',
    vibes: ['romantic', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening'],
    category: 'conversation',
    mode: 'either',
    imageSeed: 'letters',
  },
  {
    id: 'i-newdistrict',
    title: 'Be tourists in your own city',
    emoji: '🗺️',
    description:
      'Take public transport to a neighbourhood you never go to. Coffee, a wander, dinner wherever looks busy.',
    duration: 240,
    cost: 45,
    prep: 'None',
    why: 'Novelty is what makes time feel longer. An unfamiliar street does most of the work.',
    vibes: ['adventurous', 'fun', 'creative'],
    setting: 'out',
    energy: 'medium',
    weather: ['any', 'sun', 'warm', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'wholeday'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'district',
  },
  {
    id: 'i-breakfastbed',
    title: 'A morning with nothing in it',
    emoji: '☕',
    description: 'No alarm, no plans until noon. Breakfast slowly, stay where you are.',
    duration: 180,
    cost: 12,
    prep: 'Protect the morning in advance',
    why: 'Unstructured time is the rarest thing a busy couple has, and the easiest to give.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'planned',
    dayparts: ['morning', 'brunch'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'slowmorning',
  },
  {
    id: 'i-stargaze',
    title: 'Drive out of the light',
    emoji: '✨',
    description: 'Thirty minutes out of town, engine off, seats back. Blanket, thermos, no radio.',
    duration: 150,
    cost: 15,
    prep: 'Check the moon phase',
    why: 'It is very hard to talk about small grievances under that much sky.',
    vibes: ['romantic', 'adventurous', 'relaxing'],
    setting: 'out',
    energy: 'low',
    weather: ['cold', 'warm'],
    spontaneity: 'planned',
    dayparts: ['evening', 'late'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'stars',
  },
  {
    id: 'i-projectnight',
    title: 'Fix something together',
    emoji: '🔧',
    description:
      'The shelf, the bike, the drawer that sticks. Two hours, music on, then dinner you did not cook.',
    duration: 120,
    cost: 20,
    prep: 'Pick the thing in advance',
    why: 'Shared competence is underrated. Finishing something together feels good for days.',
    vibes: ['creative', 'fun'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'in_person',
    imageSeed: 'project',
  },
  {
    id: 'i-tasting',
    title: 'Blind tasting at the kitchen table',
    emoji: '🍷',
    description:
      'Three cheap bottles, or six chocolates, or four olive oils. Score them, argue, crown a winner.',
    duration: 90,
    cost: 30,
    prep: 'Shop for it together',
    why: 'Playful competition is a shortcut back to how you were early on.',
    vibes: ['fun', 'creative'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening'],
    category: 'game',
    mode: 'in_person',
    familyId: 'tasting',
    imageSeed: 'tasting',
  },
  {
    id: 'i-hike',
    title: 'A hill with a view at the top',
    emoji: '⛰️',
    description: 'Two or three hours up, sandwiches at the summit, somewhere with cake on the way home.',
    duration: 300,
    cost: 25,
    prep: 'Boots and a route',
    why: 'You cannot hurry a walk uphill. The conversation slows down to match.',
    vibes: ['adventurous', 'relaxing'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'cold', 'warm'],
    spontaneity: 'planned',
    dayparts: ['morning', 'wholeday'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'hike',
  },
  {
    id: 'i-plans',
    title: 'Plan a trip you may never take',
    emoji: '🧭',
    description:
      'Two hours, one map, one imaginary budget. Build the whole itinerary properly. Save it.',
    duration: 90,
    cost: 0,
    prep: 'None',
    why: 'Anticipating something together is measurably as good as doing it — and it sometimes turns real.',
    vibes: ['creative', 'fun', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'either',
    imageSeed: 'planning',
  },

  /* ------------------------------------------------------------------ *
   * Written against `npm run coverage` rather than to a round number.
   *
   * The holes it named, in order of how many combinations they broke:
   * free mornings at home (every vibe failed), adventurous and playful
   * indoors, free afternoons and late nights, nothing above €60 so the top
   * two budget chips were the same chip — and, loudest of all, 18 of the
   * first 24 ideas needed both people in the room, which left a couple who
   * live apart with no exact match for 71% of what they could ask for.
   * ------------------------------------------------------------------ */

  {
    id: 'i-slowcoffee',
    title: 'Coffee before the phones',
    emoji: '☕',
    description:
      'Both awake, both sitting down, neither of you having looked at a screen yet. Twenty minutes is enough.',
    duration: 30,
    cost: 0,
    prep: 'None',
    why: 'The first ten minutes of a day set its tone, and most couples spend them apart in the same room.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'spontaneous',
    dayparts: ['morning', 'brunch'],
    category: 'wellness',
    mode: 'either',
    imageSeed: 'slowcoffee',
  },
  {
    id: 'i-extrahour',
    title: 'Stay in bed an extra hour',
    emoji: '🛏️',
    description: 'No alarm, no getting up to make anything. Talk, or do not. The hour is the point.',
    duration: 60,
    cost: 0,
    prep: 'Decide the night before',
    why: 'Nobody regrets it, and almost nobody plans it — which is exactly why it needs planning.',
    vibes: ['romantic', 'relaxing'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['morning'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'extrahour',
  },
  {
    id: 'i-kitchenradio',
    title: 'Kitchen radio, before anyone is ready',
    emoji: '📻',
    description:
      'One song, loud, while the kettle boils. Neither of you is dressed and that is half of it.',
    duration: 20,
    cost: 0,
    prep: 'None',
    why: 'Being silly with someone at 7am is a different kind of intimacy from being romantic at 9pm.',
    vibes: ['fun', 'relaxing'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'spontaneous',
    dayparts: ['morning'],
    category: 'game',
    mode: 'in_person',
    imageSeed: 'kitchenradio',
  },
  {
    id: 'i-swaproutine',
    title: 'Swap your morning routines',
    emoji: '🔁',
    description:
      'You do theirs, they do yours — the order, the coffee, the music, the whole thing. Compare notes at the end.',
    duration: 45,
    cost: 0,
    prep: 'Explain yours the night before',
    why: 'You find out what the other person actually does with the first hour of their day, which is rarely what you assumed.',
    vibes: ['fun', 'adventurous'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'planned',
    dayparts: ['morning'],
    category: 'game',
    mode: 'in_person',
    imageSeed: 'swaproutine',
  },
  {
    id: 'i-firstlight',
    title: 'Walk the block before the city wakes',
    emoji: '🌫️',
    description: 'Out the door at first light, no destination, back before the shops open.',
    duration: 45,
    cost: 0,
    prep: 'Coats by the door',
    why: 'Your own street at six is a different street, and you will both notice things you walk past daily.',
    vibes: ['relaxing', 'romantic', 'adventurous'],
    setting: 'out',
    energy: 'low',
    weather: ['any', 'cold', 'warm', 'sun'],
    spontaneity: 'spontaneous',
    dayparts: ['morning'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'firstlight',
  },
  {
    id: 'i-greenbefore',
    title: 'Somewhere green before breakfast',
    emoji: '🌳',
    description:
      'The nearest park, on foot or by bike, and breakfast only once you are back. Race if you feel like it.',
    duration: 75,
    cost: 0,
    prep: 'None',
    why: 'Arriving home hungry together is a small shared achievement, and it is free.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'warm', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['morning'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'greenbefore',
  },
  {
    id: 'i-rearrange',
    title: 'Rearrange one room together',
    emoji: '🛋️',
    description:
      'Pick a room, move everything that can be moved, live with it for a week. Two hours, music on.',
    duration: 120,
    cost: 0,
    prep: 'Agree which room',
    why: 'Changing the space you live in together is a surprisingly direct way of saying things could be different.',
    vibes: ['adventurous', 'creative'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'in_person',
    imageSeed: 'rearrange',
  },
  {
    id: 'i-onehourskill',
    title: 'One hour, one skill, no quitting',
    emoji: '🎯',
    description:
      'Pick something neither of you can do — juggling, a card trick, a chord — and give it a full hour.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'An hour is long enough to get past being bad at it, which is the part most people never reach.',
    vibes: ['adventurous', 'fun', 'creative'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'either',
    imageSeed: 'onehourskill',
  },
  {
    id: 'i-twentywords',
    title: 'Twenty words of a language neither of you speaks',
    emoji: '🗣️',
    description:
      'Pick a country you might go to. Learn twenty words each, then try to hold a conversation with only those.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'Being incomprehensible together is funnier than it sounds, and the words stick.',
    vibes: ['fun', 'adventurous', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening', 'late'],
    category: 'game',
    mode: 'either',
    imageSeed: 'twentywords',
  },
  {
    id: 'i-samesofa',
    title: 'Your own books, the same sofa',
    emoji: '📖',
    description: 'An hour, each reading your own thing, no talking required. Tea at the halfway point.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'Being quiet near someone is its own kind of company, and it is the one couples stop making time for first.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'culture',
    mode: 'in_person',
    imageSeed: 'samesofa',
  },
  {
    id: 'i-benchlives',
    title: 'Pick a bench and invent lives',
    emoji: '🪑',
    description:
      'Somewhere busy. Take turns making up where each passer-by is going and why. No cruelty allowed.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'You learn what the other person finds interesting about strangers, which is a strange window into them.',
    vibes: ['fun', 'creative', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['sun', 'warm', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'conversation',
    mode: 'in_person',
    imageSeed: 'benchlives',
  },
  {
    id: 'i-midnightfridge',
    title: 'Whatever is in the fridge, at midnight',
    emoji: '🌙',
    description: 'No recipe, no shopping. Whatever is there, eaten standing up, one plate between you.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'The unplanned late meal is the one people remember, and it costs nothing but being awake.',
    vibes: ['fun', 'relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['late'],
    category: 'food',
    mode: 'in_person',
    imageSeed: 'midnightfridge',
  },
  {
    id: 'i-tripplaylist',
    title: 'The playlist for a trip you have not booked',
    emoji: '🎵',
    description:
      'Somewhere you might go one day. Build the drive-there playlist properly, twenty songs, alternating.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'It is planning without commitment, and you end up with something you will actually play.',
    vibes: ['creative', 'fun', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'creative',
    mode: 'either',
    imageSeed: 'tripplaylist',
  },
  {
    id: 'i-nightgame',
    title: 'One long game, properly',
    emoji: '🎲',
    description:
      'The board game that takes three hours. Start it late, finish it late, no phones on the table.',
    duration: 180,
    cost: 0,
    prep: 'Find the box',
    why: 'Competing against someone you love for three hours is an underrated way to spend an evening.',
    vibes: ['fun', 'adventurous'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'game',
    mode: 'in_person',
    imageSeed: 'nightgame',
  },

  /* The expensive end. Nothing here cost more than €60 before, so "Up to €80"
     and "No limit" were the same chip and the top of the range was a fiction. */

  {
    id: 'i-tastingmenu',
    title: 'The restaurant you have been saving',
    emoji: '🍽️',
    description:
      'The one you walk past and say "one day" about. Book it, dress for it, take the whole evening.',
    duration: 180,
    cost: 140,
    prep: 'Book two weeks out',
    why: 'Anticipation does most of the work, and a date you had to wait for is treated differently when it arrives.',
    vibes: ['romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['any', 'rain', 'cold', 'warm'],
    spontaneity: 'planned',
    dayparts: ['evening'],
    category: 'food',
    mode: 'in_person',
    imageSeed: 'tastingmenu',
  },
  {
    id: 'i-whoeverisplaying',
    title: 'Whoever is playing on Friday',
    emoji: '🎤',
    description:
      'Do not check who it is. Buy two tickets for whatever is on at the small venue and turn up.',
    duration: 240,
    cost: 90,
    prep: 'Tickets that morning',
    why: 'Going in with no expectations is the only way left to be genuinely surprised by an evening.',
    vibes: ['fun', 'adventurous'],
    setting: 'out',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'culture',
    mode: 'in_person',
    imageSeed: 'whoeverisplaying',
  },
  {
    id: 'i-decidenothing',
    title: 'A day where neither of you decides anything',
    emoji: '♨️',
    description:
      'Baths, steam, somewhere with no clock and no choices. Book the quiet hours and leave the phones in the locker.',
    duration: 300,
    cost: 120,
    prep: 'Book ahead',
    why: 'Most of the tiredness in a couple is decision fatigue. A day with no decisions in it is a real rest.',
    vibes: ['relaxing', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['afternoon', 'wholeday'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'decidenothing',
  },
  {
    id: 'i-firsttrain',
    title: 'First train, no return booked',
    emoji: '🚂',
    description:
      'Pick the earliest departure to somewhere neither of you has been. Come back whenever you feel like it.',
    duration: 600,
    cost: 95,
    prep: 'Check the last train home',
    why: 'A whole day with no schedule in it is rarer than a holiday and easier to arrange.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'warm', 'cold', 'any'],
    spontaneity: 'planned',
    dayparts: ['morning', 'wholeday'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'firsttrain',
  },

  /* Two kitchens, two sofas, two cities. Eighteen of the first twenty-four
     ideas needed both people in the room; a couple who live apart had no
     exact match for most of what they could ask for. Where one of these is a
     version of an in-person idea it carries the same familyId, so nobody is
     offered both forms of the same evening. */

  {
    id: 'i-videocook',
    title: 'Same recipe, two kitchens',
    emoji: '🍳',
    description:
      'Agree the recipe, shop separately, cook it at the same time with the call propped up. Eat together.',
    duration: 120,
    cost: 25,
    prep: 'Agree the recipe and shop',
    why: 'Doing the same thing at the same time is most of what being in the same room gives you.',
    vibes: ['romantic', 'creative', 'fun'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['evening'],
    category: 'food',
    mode: 'remote',
    familyId: 'cook',
    imageSeed: 'videocook',
  },
  {
    id: 'i-pressplay',
    title: 'Press play at the same second',
    emoji: '📺',
    description:
      'Something one of you loves and the other has never seen. Count down, start together, message only at the end.',
    duration: 150,
    cost: 12,
    prep: 'Both have it ready',
    why: 'Watching it apart but at the same time is not the same as watching it later — you get the same evening.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'culture',
    mode: 'remote',
    familyId: 'film',
    imageSeed: 'pressplay',
  },
  {
    id: 'i-twotables',
    title: 'Same three things, two tables',
    emoji: '🍫',
    description:
      'Agree on three of something — chocolate, cheap wine, crisps. Buy the same three, score them apart, compare.',
    duration: 90,
    cost: 30,
    prep: 'Agree the three and shop',
    why: 'Disagreeing about which one is best is a real conversation, and it works perfectly down a phone line.',
    vibes: ['fun', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['evening'],
    category: 'game',
    mode: 'remote',
    familyId: 'tasting',
    imageSeed: 'twotables',
  },
  {
    id: 'i-walkandtalk',
    title: 'Walk your own streets, together',
    emoji: '🚶',
    description:
      'Both of you outside, both walking, one call. Describe what you are passing. Forty minutes goes quickly.',
    duration: 45,
    cost: 0,
    prep: 'Headphones',
    why: 'Walking makes people talk differently, and it works even when the pavements are in different countries.',
    vibes: ['relaxing', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['any', 'cold', 'warm', 'sun'],
    spontaneity: 'spontaneous',
    dayparts: ['morning', 'afternoon', 'evening'],
    category: 'outdoors',
    mode: 'remote',
    imageSeed: 'walkandtalk',
  },
  {
    id: 'i-samechapter',
    title: 'Read the same chapter tonight',
    emoji: '📗',
    description:
      'One book, two copies, one chapter a night. Say one thing about it before you sleep. No spoilers ahead.',
    duration: 45,
    cost: 18,
    prep: 'Both get the book',
    why: 'A book you are both inside gives you something to talk about that is not logistics or the day you had.',
    vibes: ['relaxing', 'romantic', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['evening', 'late'],
    category: 'culture',
    mode: 'remote',
    imageSeed: 'samechapter',
  },
  {
    id: 'i-twomuseums',
    title: 'Two museums, one hour, photos only',
    emoji: '🖼️',
    description:
      'Each of you goes somewhere near you. One hour, send three photographs each, explain them afterwards.',
    duration: 90,
    cost: 24,
    prep: 'Check opening times',
    why: 'You end up seeing a city you have never been to through the eyes of someone who chose what to show you.',
    vibes: ['creative', 'adventurous', 'fun'],
    setting: 'out',
    energy: 'low',
    weather: ['rain', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon'],
    category: 'culture',
    mode: 'remote',
    imageSeed: 'twomuseums',
  },
  {
    id: 'i-morningapart',
    title: 'Coffee at the same time, two cities',
    emoji: '📱',
    description:
      'Same hour, both sitting down, both with a coffee. Twenty minutes before either of you starts the day.',
    duration: 30,
    cost: 0,
    prep: 'Agree the hour',
    why: 'Starting the day with the same person is most of what living together gives you, and it survives distance.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'planned',
    dayparts: ['morning', 'brunch'],
    category: 'wellness',
    mode: 'remote',
    imageSeed: 'morningapart',
  },
  {
    id: 'i-buildit',
    title: 'Build the same thing, badly',
    emoji: '🧩',
    description:
      'The same cheap kit, model, or puzzle, ordered to both addresses. Open them on a call and race.',
    duration: 120,
    cost: 35,
    prep: 'Order two of the same',
    why: 'Being bad at something in front of each other is disarming, and it does not need a shared table.',
    vibes: ['fun', 'creative', 'adventurous'],
    setting: 'home',
    energy: 'medium',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'planned',
    dayparts: ['afternoon', 'evening'],
    category: 'creative',
    mode: 'remote',
    imageSeed: 'buildit',
  },

  /* Second tranche, aimed at what the first one left: free outdoor evenings
     with any energy in them, and — for couples apart — playful mornings and
     anything at all late at night. */

  {
    id: 'i-getlost',
    title: 'Get lost on purpose',
    emoji: '🧭',
    description:
      'Walk or ride for forty minutes taking only turns you have never taken. Phones stay in pockets until you want them.',
    duration: 90,
    cost: 0,
    prep: 'None',
    why: 'Not knowing where you are is the cheapest way to feel like you went somewhere.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'medium',
    weather: ['sun', 'warm', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'getlost',
  },
  {
    id: 'i-highestpoint',
    title: 'The highest point you can walk to',
    emoji: '🌃',
    description:
      'A hill, a car park roof, a bridge. Go after dark, look at the lights, walk back down.',
    duration: 90,
    cost: 0,
    prep: 'Something warm',
    why: 'Every place has one, almost nobody goes, and it makes an ordinary town look like somewhere worth living.',
    vibes: ['adventurous', 'romantic'],
    setting: 'out',
    energy: 'medium',
    weather: ['cold', 'warm', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'outdoors',
    mode: 'in_person',
    imageSeed: 'highestpoint',
  },
  {
    id: 'i-emptyswings',
    title: 'The playground, after everyone has gone',
    emoji: '🎠',
    description: 'Swings at eleven at night. See who can go higher. Nobody is watching and that is the point.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'Being briefly ridiculous together undoes more of a bad week than talking about it does.',
    vibes: ['fun', 'adventurous'],
    setting: 'out',
    energy: 'medium',
    weather: ['warm', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'game',
    mode: 'in_person',
    imageSeed: 'emptyswings',
  },
  {
    id: 'i-guessbreakfast',
    title: 'Two breakfasts, one call',
    emoji: '🥣',
    description:
      'Describe what you are eating without naming it. They guess. Loser picks what you both eat tomorrow.',
    duration: 30,
    cost: 0,
    prep: 'None',
    why: 'A daft game first thing is a better start than a status update about the day ahead.',
    vibes: ['fun', 'relaxing'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold', 'sun'],
    spontaneity: 'spontaneous',
    dayparts: ['morning', 'brunch'],
    category: 'game',
    mode: 'remote',
    imageSeed: 'guessbreakfast',
  },
  {
    id: 'i-samesky',
    title: 'Same sky, two windows',
    emoji: '🌌',
    description:
      'Both of you outside or at a window at the same hour. Find one thing you can both see. Stay on the line a while.',
    duration: 45,
    cost: 0,
    prep: 'Agree the hour',
    why: 'The moon is the same one. It is a small thing and it does more than it should.',
    vibes: ['romantic', 'relaxing', 'adventurous'],
    setting: 'out',
    energy: 'low',
    weather: ['cold', 'warm', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'outdoors',
    mode: 'remote',
    imageSeed: 'samesky',
  },
  {
    id: 'i-latequiz',
    title: 'Midnight quiz, no googling',
    emoji: '❓',
    description:
      'Ten questions each, written in ten minutes, asked down the phone. Absurd categories encouraged.',
    duration: 60,
    cost: 0,
    prep: 'Ten minutes to write them',
    why: 'What someone chooses to ask you says more than what they answer.',
    vibes: ['fun', 'adventurous'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'game',
    mode: 'remote',
    imageSeed: 'latequiz',
  },
  {
    id: 'i-streetview',
    title: 'Show me where you grew up',
    emoji: '🗺️',
    description:
      'Share a screen, walk them down the street you grew up on, then swap. Stop wherever there is a story.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'Everyone has ten stories attached to one street, and almost nobody gets asked for them.',
    vibes: ['romantic', 'creative', 'adventurous'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening', 'late'],
    category: 'conversation',
    mode: 'remote',
    imageSeed: 'streetview',
  },
  {
    id: 'i-marketapart',
    title: 'Two markets, one shopping list',
    emoji: '🧺',
    description:
      'Same list, different cities, one hour. Send photographs of what you found and what you had to substitute.',
    duration: 75,
    cost: 25,
    prep: 'Write the list together',
    why: 'You get a real look at where the other one actually lives, which photographs of landmarks never give you.',
    vibes: ['fun', 'adventurous', 'creative'],
    setting: 'out',
    energy: 'medium',
    weather: ['sun', 'warm', 'any'],
    spontaneity: 'planned',
    dayparts: ['morning', 'brunch', 'afternoon'],
    category: 'food',
    mode: 'remote',
    imageSeed: 'marketapart',
  },

  /* Third tranche, all remote, all aimed at what living apart still could not
     ask for: something with a bit of daring in it before work, something
     playful outdoors in the morning, and a quiet afternoon that is not a
     phone call about logistics. */

  {
    id: 'i-coldstart',
    title: 'Cold shower, both of you, on three',
    emoji: '🥶',
    description:
      'Count down together, thirty seconds each, stay on the call for the shouting. Coffee immediately after.',
    duration: 20,
    cost: 0,
    prep: 'None',
    why: 'Doing something slightly awful at the same moment is the closest thing to being in the same room.',
    vibes: ['adventurous', 'fun'],
    setting: 'home',
    energy: 'high',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['morning'],
    category: 'wellness',
    mode: 'remote',
    imageSeed: 'coldstart',
  },
  {
    id: 'i-dawnrace',
    title: 'Out the door in ten minutes, both of you',
    emoji: '👟',
    description:
      'Whoever is first to send a photograph from somewhere green wins. No cars. Losers make the plans next time.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'A reason to be outside early is worth more than the discipline you were going to rely on.',
    vibes: ['adventurous', 'fun'],
    setting: 'out',
    energy: 'high',
    weather: ['sun', 'warm', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['morning', 'brunch'],
    category: 'outdoors',
    mode: 'remote',
    imageSeed: 'dawnrace',
  },
  {
    id: 'i-quietcall',
    title: 'An afternoon with the call left open',
    emoji: '🔇',
    description:
      'Both doing your own thing, camera on, nobody obliged to talk. Say something when there is something to say.',
    duration: 120,
    cost: 0,
    prep: 'None',
    why: 'What people miss most about living together is not conversation, it is the company of someone not talking.',
    vibes: ['relaxing', 'romantic'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening'],
    category: 'conversation',
    mode: 'remote',
    imageSeed: 'quietcall',
  },
  {
    id: 'i-tenblocks',
    title: 'Ten blocks you have never walked',
    emoji: '📍',
    description:
      'Each of you picks a direction neither has gone and walks it for half an hour, sending pictures as you go.',
    duration: 60,
    cost: 0,
    prep: 'None',
    why: 'You both come back with something to tell, which is harder than it sounds when you speak every day.',
    vibes: ['adventurous', 'fun', 'creative'],
    setting: 'out',
    energy: 'medium',
    weather: ['sun', 'warm', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['morning', 'afternoon', 'evening'],
    category: 'outdoors',
    mode: 'remote',
    imageSeed: 'tenblocks',
  },
  {
    id: 'i-slowsunday',
    title: 'The same album, start to finish',
    emoji: '💿',
    description:
      'One record neither of you has heard properly. Press play together, no talking until the last track ends.',
    duration: 45,
    cost: 0,
    prep: 'Pick it beforehand',
    why: 'Forty minutes of not talking, spent deliberately, is a different silence from the one where nobody rang.',
    vibes: ['relaxing', 'romantic', 'creative'],
    setting: 'home',
    energy: 'low',
    weather: ['any', 'rain', 'cold'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'evening', 'late'],
    category: 'culture',
    mode: 'remote',
    imageSeed: 'slowsunday',
  },

  {
    id: 'i-nighthunt',
    title: 'Midnight scavenger hunt, two cities',
    emoji: '🔦',
    description:
      'Name five things the other has to photograph outside within twenty minutes. A red door, someone laughing, the worst sign in town.',
    duration: 45,
    cost: 0,
    prep: 'None',
    why: 'It sends you both outside at an hour you would not have gone, looking for something silly, on purpose.',
    vibes: ['fun', 'adventurous'],
    setting: 'out',
    energy: 'medium',
    weather: ['warm', 'cold', 'any'],
    spontaneity: 'spontaneous',
    dayparts: ['evening', 'late'],
    category: 'game',
    mode: 'remote',
    imageSeed: 'nighthunt',
  },

  {
    id: 'i-slowpark',
    title: 'An afternoon on the same blanket',
    emoji: '🌿',
    description:
      'The nearest patch of grass, a blanket, nothing to do and nowhere to be after. Fall asleep if you like.',
    duration: 120,
    cost: 0,
    prep: 'A blanket',
    why: 'Doing nothing indoors feels like a wasted afternoon; doing nothing outdoors feels like a holiday.',
    vibes: ['relaxing', 'romantic'],
    setting: 'out',
    energy: 'low',
    weather: ['sun', 'warm'],
    spontaneity: 'spontaneous',
    dayparts: ['afternoon', 'brunch'],
    category: 'wellness',
    mode: 'in_person',
    imageSeed: 'slowpark',
  },
];
